# Generated by Django 4.2.4 on 2023-08-23 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id_book', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('lancamento', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('paginas', models.IntegerField()),
                ('editora', models.CharField(max_length=255)),
                ('criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
